# Cross Validation

In [33]:
import numpy as np

from sklearn.datasets import load_digits

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import cross_val_score

from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import RepeatedStratifiedKFold

# Load Data

In [2]:
digits = load_digits()

In [ ]:
X = digits.data 
y = digits.target 

# 1. train_test_split

In [14]:
# X_train, X_test, y_train, y_test = train_test_split(X , y , test_size= 0.2)
X_train, X_test, y_train, y_test = train_test_split(X , y , train_size= 0.8)

In [15]:
model1 = LogisticRegression(solver= "liblinear")
model1.fit(X_train, y_train)

model1.score(X_test, y_test)

0.9527777777777777

# 2. K-Fold

In [19]:
k_folds = 5 

scores = cross_val_score(model1, X ,y , cv = k_folds)
scores

array([0.92222222, 0.88333333, 0.95264624, 0.95821727, 0.89415042])

In [21]:
score_mean = np.average(scores)

score_mean

0.9221138966264315

In [22]:
# Prepare my Training data in folds
k_folds = KFold(n_splits= 5, shuffle= True)
# k_folds = KFold(n_splits= 5, shuffle= True, random_state= 40)


# Use the folds in the traing phase of the model
scores = cross_val_score(model1, X ,y , cv = k_folds)
scores

array([0.96388889, 0.93611111, 0.96657382, 0.96100279, 0.96657382])

In [23]:
score_mean = np.average(scores)

score_mean

0.9588300835654596

In [25]:

# K-Folder
k_folds = KFold(n_splits= 10, shuffle= True, random_state= 40)

# Models
model2 = RandomForestClassifier(n_estimators= 5, random_state= 40)
model3 = RandomForestClassifier(n_estimators= 50, random_state= 40)
model4 = RandomForestClassifier(n_estimators= 500, random_state= 40)

# Cross validation
score2 = cross_val_score(model2, X ,y , cv = k_folds)
score3 = cross_val_score(model3, X ,y , cv = k_folds)
score4 = cross_val_score(model4, X ,y , cv = k_folds)

# Printing the average
print(f"Average Score 2 : {np.average(score2)}")
print(f"Average Score 3 : {np.average(score3)}")
print(f"Average Score 4 : {np.average(score4)}")


Average Score 2 : 0.9221073867163252
Average Score 3 : 0.9766201117318436
Average Score 4 : 0.9788423339540658


# 3. StratifiedKFold

In [30]:
# Prepare my Training data in folds
k_folds = StratifiedKFold(n_splits= 5, shuffle= True)
# k_folds = KFold(n_splits= 5, shuffle= True, random_state= 40)


# Use the folds in the traing phase of the model
scores = cross_val_score(model1, X ,y , cv = k_folds)
scores

array([0.95555556, 0.95277778, 0.95821727, 0.95821727, 0.96657382])

# 4. Repeated StratifiedKFold

In [35]:
# Prepare my Training data in folds
k_folds = RepeatedStratifiedKFold(n_splits= 5, n_repeats= 3)


# k_folds = KFold(n_splits= 5, shuffle= True, random_state= 40)


# Use the folds in the traing phase of the model
scores = cross_val_score(model1, X ,y , cv = k_folds)
scores

print(f"Average Score  : {np.average(scores)}")


Average Score  : 0.9586325183121842


In [36]:
# Prepare my Training data in folds
k_folds = RepeatedStratifiedKFold(n_splits= 5, n_repeats= 3)


# k_folds = KFold(n_splits= 5, shuffle= True, random_state= 40)


# Use the folds in the traing phase of the model
scores = cross_val_score(model4, X ,y , cv = k_folds)
scores

print(f"Average Score  : {np.average(scores)}")

Average Score  : 0.9755199628597956
